### ISSUE TITLE
Feature Request: Clipboard copy/paste for PICTURE commands in Windows

### ISSUE THREAD

**Issue by vga-256** [AGKorson/WinAGI-GDS#2]
I've just started working with WinAGI for an art project, and I'm really impressed with how well-integrated the tools are with one another. It very much reminds me of working with AGS.

I have a specific feature request that I'm not sure is possible, but I thought I'd ask anyway:

I'm extracting all of the draw commands from a PICTURE file, and translating them into another drawing language. While I can see all of the scripting commands in the WinAGI listbox, copying them (via Command List: Copy Commands) does not allow me to paste them into a text file for manual editing. They appear to only be paste-able within WinAGI itself, and not copied to the system clipboard.

Is it currently possible in WinAGI to extract the command list as a text file? If not, would it be possible to somehow "Copy Commands as Text" so they could be pasted elsewhere?

Thanks for your time!

**Comment by AGKorson** [comment]
@vga-256 , thx for the compliments. I'm glad you find WinAGI useful.

I am not currently doing any work on this C# version repo, but am about to release an update to the original VB6 version. I think I can add your feature request to that release, which will be out by end of October. Check out https://sciprogramming.com/community/index.php to watch for that - I'll announce it there when it's ready. 

Regards,
Andrew

**Comment by AGKorson** [comment]
Email reply test

 

From: vga256 ***@***.***> 
Sent: Monday, October 9, 2023 1:01 PM
To: AGKorson/WinAGI-GDS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AGKorson/WinAGI-GDS] Feature Request: Clipboard copy/paste for PICTURE commands in Windows (Issue #2)

 

I've just started working with WinAGI for an art project, and I'm really impressed with how well-integrated the tools are with one another. It very much reminds me of working with AGS.

I have a specific feature request that I'm not sure is possible, but I thought I'd ask anyway:

I'm extracting all of the draw commands from a PICTURE file, and translating them into another drawing language. While I can see all of the scripting commands in the WinAGI listbox, copying them (via Command List: Copy Commands) does not allow me to paste them into a text file for manual editing. They appear to only be paste-able within WinAGI itself, and not copied to the system clipboard.

Is it currently possible in WinAGI to extract the command list as a text file? If not, would it be possible to somehow "Copy Commands as Text" so they could be pasted elsewhere?

Thanks for your time!

**Comment by AGKorson** [comment]
@vga-256, I've added that feature to WinAGI-VB. but I am not sure what format you would like for the output. Please contact me on https://sciprogramming.com/community/index.php, so we can have a discussion on that. (I don't see a way to have private messages on github).

**Comment by vga-256** [comment]
Wild! Looking forward to it. Thank you.

**Comment by vga-256** [comment]
As my account has been waiting admin approval over at the sci programming forums for a couple of days, I won't count on that getting done any time soon.

Format-wise, I'm just looking for something that would represent the text/strings of the AGI PICTURE scripting language - pretty much what you already see as drawing commands in the dropdown box when a PICTURE is select. Later on, I'll be translating those drawing commands into another vector language.

**Comment by AGKorson** [comment]
@vga-256, I just released a new version (2.3.2) that includes the feature you've requested. Check it out at http://agiwiki.sierrahelp.com/index.php?title=File:WinAGI_2_3_2.zip.
